# Copyright 2018 The Bazel Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------
# Modified 2025 by @tragisch <https://github.com/tragisch>
# SPDX-License-Identifier: MIT

"""Installer Rules

Starlark rules for installing files using Bazel.
"""

load("@bazel_skylib//lib:paths.bzl", "paths")
load("@bazel_skylib//lib:shell.bzl", "shell")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")
# Simple license collection without external dependencies
# Using native sh_binary instead of rules_shell for simplicity
# load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

_INSTALLER_GEN_SUFFIX = "_gen"
_TEMPLATE_TARGET = "//lib/installer:installer_template"

# License files can be included via the data parameter

def _install_files_depset(target):
    direct = []
    transitive = []

    # DefaultInfo Provider - precompiled artifacts
    default_info = target[DefaultInfo]
    if default_info.files:
        transitive.append(default_info.files)
    if default_info.default_runfiles:
        transitive.append(default_info.default_runfiles.files)
    if default_info.files_to_run and default_info.files_to_run.executable:
        direct.append(default_info.files_to_run.executable)

    # CcInfo Provider - only direct (no transitive dependencies)
    if CcInfo in target:
        cc_info = target[CcInfo]
        if hasattr(cc_info.compilation_context, "direct_headers"):
            # direct_headers is a list, so add it to direct
            direct.extend(cc_info.compilation_context.direct_headers)

    if direct or transitive:
        return depset(direct = direct, transitive = transitive)
    return None

def _extract_target_name(installer_name):
    """Extract the actual target name from installer name, removing 'install_' prefix if present."""
    if installer_name.startswith("install_"):
        return installer_name[8:]  # Remove "install_" prefix
    return installer_name

def _get_source_path(file, workspace):
    """Generate appropriate runfiles path for the installer script."""
    short_path = file.short_path

    # Remove any leading ../ from the path
    if short_path.startswith("../"):
        short_path = short_path[3:]
    if short_path.startswith("../"):
        short_path = short_path[3:]

    # For external repositories, use the adjusted short_path directly
    if workspace and workspace != "_main":
        return short_path

    # For local files, ensure they have the _main/ prefix
    if not short_path.startswith("_main/"):
        return "_main/" + short_path
    return short_path

def _gen_install_binary_impl(ctx):
    transitive_runfiles = []
    sources = []
    targets = []
    license_json_file = None

    for input in ctx.attr.data:
        input_files = _install_files_depset(input)
        if not input_files:
            continue
        transitive_runfiles.append(input_files)

        workspace = (input.label.workspace_name or ctx.workspace_name)

        for file in input_files.to_list():
            # Check if this is a license JSON file
            if file.basename.endswith("_licenses.json"):
                license_json_file = file
                continue  # Don't install the JSON file itself

            # Use corrected path generation
            source_path = _get_source_path(file, workspace)
            sources.append(source_path)

            target = paths.join(ctx.attr.target_subdir, paths.basename(file.short_path))
            targets.append(target)

    ctx.actions.expand_template(
        output = ctx.outputs.out,
        template = ctx.file._template,
        substitutions = {
            "@@SOURCE_FILES@@": shell.array_literal(sources),
            "@@TARGET_NAMES@@": shell.array_literal(targets),
            "@@EXECUTABLE@@": shell.quote(repr(ctx.attr.executable)),
            "@@LICENSE_JSON@@": license_json_file.short_path if license_json_file else "",
            "@@TARGET_NAME@@": shell.quote(_extract_target_name(ctx.label.name[1:-len(_INSTALLER_GEN_SUFFIX)])),
            "@@INSTALLER_LABEL@@": shell.quote("@{}//{}:{}".format(
                ctx.workspace_name,
                ctx.label.package,
                # Strip leading '_' and suffix form the name.
                ctx.label.name[1:-len(_INSTALLER_GEN_SUFFIX)],
            )),
            "@@GENERATED_WARNING@@": (
                "# DO NOT EDIT THIS FILE.\n" +
                "# It was generated by {} in @{}.\n" +
                "#"
            ).format(ctx.label, ctx.workspace_name),
            "@@SYSTEM_INTEGRATION@@": shell.quote(repr(ctx.attr.system_integration)),
        },
        is_executable = True,
    )

    return [DefaultInfo(
        executable = ctx.outputs.out,
        runfiles = ctx.runfiles(
            files = [ctx.outputs.out] + ([license_json_file] if license_json_file else []),
            transitive_files = depset(transitive = transitive_runfiles),
        ),
    )]

def _compilation_mode_transition_impl(settings, attr):
    mode = attr.compilation_mode or settings["//command_line_option:compilation_mode"]
    return {"//command_line_option:compilation_mode": mode}

_compilation_mode_transition = transition(
    implementation = _compilation_mode_transition_impl,
    inputs = ["//command_line_option:compilation_mode"],
    outputs = ["//command_line_option:compilation_mode"],
)

_gen_installer = rule(
    implementation = _gen_install_binary_impl,
    attrs = {
        "compilation_mode": attr.string(),
        "data": attr.label_list(
            mandatory = True,
            allow_files = True,
            cfg = _compilation_mode_transition,
        ),
        "executable": attr.bool(default = True),
        "target_subdir": attr.string(default = ""),
        "system_integration": attr.bool(default = False),
        "_template": attr.label(
            allow_single_file = True,
            default = Label(_TEMPLATE_TARGET),
        ),
        "_allowlist_function_transition": attr.label(
            default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
        ),
    },
    executable = True,
    outputs = {
        "out": "%{name}.sh",
    },
)

def installer(name, data, compilation_mode = "opt", executable = True, target_subdir = "", system_integration = False):
    """Creates an installer

    This rule creates an installer for targets in data. Running the installer
    copies built targets to a given prefix. The prefix has to be passed as an
    argument to the installer.

    Args:
      name: A unique name of this rule.
      compilation_mode: If not empty, sets compilation_mode of targets in data.
      data: Targets to be installed. File names will not be changed.
      executable: If True, the copied files will be set as executable.
      target_subdir: Optional subdir under the prefix where the files will be
                     placed.
      system_integration: If True, installer will create symlinks in system directories.
    """
    installer_name = "_{}{}".format(name, _INSTALLER_GEN_SUFFIX)

    # License files should be included in data parameter by user
    _gen_installer(
        name = installer_name,
        compilation_mode = compilation_mode,
        data = data,
        executable = executable,
        target_subdir = target_subdir,
        system_integration = system_integration,
    )

    # Create final sh_binary target
    sh_binary(
        name = name,
        srcs = [":" + installer_name],
        data = [":" + installer_name],
        deps = ["@bazel_tools//tools/bash/runfiles"],
    )
