# Copyright 2025 @tragisch <https://github.com/tragisch>
# SPDX-License-Identifier: MIT
#
# This module provides license reporting functionality inspired by and compatible with
# @rules_license (Apache 2.0) but reimplemented for better integration and visibility.
#
# API-compatible reimplementation of:
# - @rules_license//rules_gathering:generate_sbom.bzl
# - @rules_license//rules_gathering:gather_metadata.bzl
# - @rules_license//rules:gather_licenses_info.bzl

"""License Report Generation Rules

Custom license collection and reporting rules based on rules_license framework.
Provides full API compatibility with @rules_license while offering enhanced 
visibility and integration capabilities.
"""

load(
    "@rules_license//rules:gather_licenses_info.bzl",
    "gather_licenses_info",
    "write_licenses_info",
)
load(
    "@rules_license//rules_gathering:gather_metadata.bzl",
    "gather_metadata_info",
    "write_metadata_info",
)
load(
    "@rules_license//rules_gathering:gathering_providers.bzl",
    "TransitiveLicensesInfo",
)

def _license_report_impl(ctx):
    """Implementation for license_report rule.

    Collects license information from dependencies and writes it as JSON.
    Uses the official rules_license gather_licenses_info aspect.
    """

    # Use the official write_licenses_info function from rules_license
    write_licenses_info(ctx, ctx.attr.deps, ctx.outputs.out)

    return [DefaultInfo(files = depset([ctx.outputs.out]))]

_license_report = rule(
    implementation = _license_report_impl,
    doc = """Internal implementation for license_report() macro.""",
    attrs = {
        "deps": attr.label_list(
            doc = """List of targets to collect LicenseInfo for.""",
            aspects = [gather_licenses_info],
        ),
        "out": attr.output(
            doc = """Output JSON file containing license information.""",
            mandatory = True,
        ),
    },
)

def license_report(name, deps, out = None, **kwargs):
    """Collects license information for a set of targets and writes as JSON.

    This rule uses the official rules_license framework to gather license
    information from all transitive dependencies. The output is a single
    JSON file containing detailed license information for each dependency.

    The JSON schema follows the rules_license standard format with entries
    containing license text, attribution information, and dependency details.

    Args:
      name: The target name.
      deps: A list of targets to collect LicenseInfo for. The output includes
            license information for all transitive dependencies.
      out: The output file name. Default: <name>.json.
      **kwargs: Additional arguments passed to the underlying rule.

    Example:
      license_report(
          name = "project_licenses",
          deps = [":my_app", "//third_party:all_deps"],
          out = "licenses.json",
      )
    """
    if not out:
        out = name + ".json"

    _license_report(
        name = name,
        deps = deps,
        out = out,
        **kwargs
    )

def _license_summary_impl(ctx):
    """Implementation for license_summary rule.

    Creates a human-readable license summary from license report JSON.
    """

    # Run the external summary generator
    ctx.actions.run(
        inputs = [ctx.file.license_json],
        outputs = [ctx.outputs.out],
        executable = ctx.executable._summary_generator,
        arguments = [ctx.file.license_json.path, ctx.outputs.out.path],
        mnemonic = "LicenseSummary",
        progress_message = "Creating license summary for %s" % ctx.label,
    )

    return [DefaultInfo(files = depset([ctx.outputs.out]))]

_license_summary = rule(
    implementation = _license_summary_impl,
    doc = """Internal implementation for license_summary() macro.""",
    attrs = {
        "license_json": attr.label(
            doc = """License JSON file to summarize.""",
            allow_single_file = [".json"],
            mandatory = True,
        ),
        "out": attr.output(
            doc = """Output summary text file.""",
            mandatory = True,
        ),
        "_summary_generator": attr.label(
            default = Label("//lib/license:license_summary_generator"),
            executable = True,
            cfg = "exec",
        ),
    },
)

def license_summary(name, license_json, out = None, **kwargs):
    """Creates a human-readable summary from a license JSON report.

    Takes a JSON file generated by license_report() and creates a
    human-readable text summary grouped by license type.

    Args:
      name: The target name.
      license_json: Label of the JSON file containing license information.
      out: The output summary file name. Default: <name>.txt.
      **kwargs: Additional arguments passed to the underlying rule.

    Example:
      license_summary(
          name = "license_summary",
          license_json = ":project_licenses",
          out = "LICENSE_SUMMARY.txt",
      )
    """
    if not out:
        out = name + ".txt"

    _license_summary(
        name = name,
        license_json = license_json,
        out = out,
        **kwargs
    )

def get_licenses_mapping(deps, warn = False):
    """Creates list of entries representing all licenses for the deps.

    This is a reimplementation of the original get_licenses_mapping function
    from @rules_license//rules_gathering:generate_sbom.bzl.

    Args:
      deps: a list of deps which should have TransitiveLicensesInfo providers.
            This requires that you have run the gather_licenses_info
            aspect over them
      warn: boolean, if true, display output about legacy targets that need
            update

    Returns:
      {File:package_name}
    """
    tls = []
    for dep in deps:
        if TransitiveLicensesInfo in dep:
            lds = dep[TransitiveLicensesInfo].licenses
            tls.append(lds)

    ds = depset(transitive = tls)

    # Ignore any legacy licenses that may be in the report
    mappings = {}
    for lic in ds.to_list():
        if type(lic.license_text) == "File":
            mappings[lic.license_text] = lic.package_name
        elif warn:
            # buildifier: disable=print
            print("Legacy license %s not included, rule needs updating" % lic.license_text)

    return mappings

def _license_manifest_impl(ctx):
    """Implementation for license_manifest rule.

    Creates a manifest file listing all license files and their associated packages.
    Uses the same approach as the original @rules_license manifest implementation.
    """

    # Use our reimplemented get_licenses_mapping function
    mappings = get_licenses_mapping(ctx.attr.deps, ctx.attr.warn_on_legacy_licenses)

    # Create manifest content in the same format as the original
    manifest_content = [",".join([f.path, p]) for (f, p) in mappings.items()]

    ctx.actions.write(
        output = ctx.outputs.out,
        content = "\n".join(sorted(manifest_content)),
    )

    # Return both the manifest file and the actual license files (like the original)
    return [DefaultInfo(files = depset([ctx.outputs.out] + list(mappings.keys())))]

_license_manifest = rule(
    implementation = _license_manifest_impl,
    doc = """Internal implementation for license_manifest() macro.
    
    Mimics the original @rules_license manifest implementation.""",
    attrs = {
        "deps": attr.label_list(
            doc = """List of targets to collect license files for.""",
            aspects = [gather_licenses_info],
        ),
        "out": attr.output(
            doc = """Output manifest file.""",
            mandatory = True,
        ),
        "warn_on_legacy_licenses": attr.bool(
            doc = """Whether to warn about legacy licenses that need updating.""",
            default = False,
        ),
    },
)

def license_manifest(name, deps, out = None, warn_on_legacy_licenses = False, **kwargs):
    """Creates a manifest file listing all license files and their packages.

    The manifest includes all license files from transitive dependencies
    and can be used for downstream tools that need to process license files
    or for creating automated compliance reports.

    Args:
      name: The target name.
      deps: A list of targets to collect license files for. The manifest will
            include license information for all transitive dependencies.
      out: The output manifest file name. Default: <name>.manifest.
      warn_on_legacy_licenses: Whether to print warnings about legacy licenses
                              that need updating. Default: False.
      **kwargs: Additional arguments passed to the underlying rule.

    Example:
      license_manifest(
          name = "project_license_manifest",
          deps = [":my_app"],  # Will collect ALL transitive dependencies
          out = "licenses.manifest",
      )
    """
    if not out:
        out = name + ".manifest"

    _license_manifest(
        name = name,
        deps = deps,
        out = out,
        warn_on_legacy_licenses = warn_on_legacy_licenses,
        **kwargs
    )

def _enhanced_license_report_impl(ctx):
    """Implementation for enhanced_license_report rule.

    Creates both JSON report and additional metadata using proper aspects.
    This provides comprehensive information with both standard license data
    and enhanced metadata.
    """

    # Create standard JSON report using the licenses_deps with gather_licenses_info aspect
    json_file = ctx.actions.declare_file(ctx.label.name + ".json")
    write_licenses_info(ctx, ctx.attr.licenses_deps, json_file)

    # Create enhanced metadata report using the metadata_deps with gather_metadata_info aspect
    metadata_file = ctx.actions.declare_file(ctx.label.name + "_metadata.json")
    write_metadata_info(ctx, ctx.attr.metadata_deps, metadata_file)

    return [
        DefaultInfo(files = depset([json_file, metadata_file])),
        OutputGroupInfo(
            licenses = depset([json_file]),
            metadata = depset([metadata_file]),
        ),
    ]

_enhanced_license_report = rule(
    implementation = _enhanced_license_report_impl,
    doc = """Internal implementation for enhanced_license_report() macro.""",
    attrs = {
        "licenses_deps": attr.label_list(
            doc = """List of targets to collect standard license information for.""",
            aspects = [gather_licenses_info],
        ),
        "metadata_deps": attr.label_list(
            doc = """List of targets to collect comprehensive metadata for.""",
            aspects = [gather_metadata_info],
        ),
    },
)

def enhanced_license_report(name, deps, **kwargs):
    """Creates comprehensive license and metadata reports.

    This rule generates both a standard license JSON report and an enhanced
    metadata report using the appropriate aspects for each type of information.

    Outputs:
    - name.json: Standard license information (using gather_licenses_info)
    - name_metadata.json: Enhanced metadata information (using gather_metadata_info)

    Args:
      name: The target name.
      deps: A list of targets to collect information for.
      **kwargs: Additional arguments passed to the underlying rule.

    Example:
      enhanced_license_report(
          name = "comprehensive_report",
          deps = [":all_deps"],
      )
    """
    _enhanced_license_report(
        name = name,
        licenses_deps = deps,
        metadata_deps = deps,
        **kwargs
    )

def _generate_sbom_impl(ctx):
    """Implementation for generate_sbom rule.

    Mimics the official @rules_license//rules_gathering:generate_sbom.bzl functionality
    exactly, but uses our own SBOM generation script instead of the inaccessible write_sbom tool.
    """

    # Step 1: Gather comprehensive metadata (exactly like the original)
    licenses_file = ctx.actions.declare_file("_%s_licenses_info.json" % ctx.label.name)
    write_metadata_info(ctx, ctx.attr.deps, licenses_file)

    # Step 2: Run our external SBOM generator (mimicking the original's action structure)
    inputs = [licenses_file]
    outputs = [ctx.outputs.out]
    args = ctx.actions.args()
    args.add("--licenses_info", licenses_file.path)
    args.add("--out", ctx.outputs.out.path)

    ctx.actions.run(
        mnemonic = "CreateSBOM",
        progress_message = "Creating SBOM for %s" % ctx.label,
        inputs = inputs,
        outputs = outputs,
        executable = ctx.executable._sbom_generator,
        arguments = [args],
    )

    return [
        DefaultInfo(files = depset(outputs)),
        OutputGroupInfo(licenses_file = depset([licenses_file])),
    ]

_generate_sbom = rule(
    implementation = _generate_sbom_impl,
    doc = """Internal implementation for generate_sbom() macro.

    Mimics @rules_license//rules_gathering:generate_sbom.bzl but uses
    our own SBOM generation instead of the inaccessible write_sbom tool.""",
    attrs = {
        "deps": attr.label_list(
            doc = """List of targets to collect metadata for SBOM generation.""",
            aspects = [gather_metadata_info],  # Use the comprehensive aspect like the original
        ),
        "out": attr.output(
            doc = """Output SPDX SBOM file.""",
            mandatory = True,
        ),
        "_sbom_generator": attr.label(
            default = Label("//lib/license:sbom_generator"),
            executable = True,
            cfg = "exec",
        ),
    },
)

def generate_sbom(name, deps, out = None, **kwargs):
    """Generates an SPDX-style SBOM (Software Bill of Materials).

    This function replicates the API and functionality of the official
    @rules_license//rules_gathering:generate_sbom.bzl exactly, but works around
    the visibility/compatibility issues with the write_sbom tool.

    Creates a standards-compliant SPDX 2.3 SBOM in JSON format containing
    all license information for the specified dependencies. Like the original,
    this automatically collects license information from ALL transitive
    dependencies - you only need to specify your top-level targets.

    Args:
      name: The target name.
      deps: A list of targets to include in the SBOM. The SBOM will automatically
            include license information for all transitive dependencies.
      out: The output SBOM file name. Default: name.spdx.json.
      **kwargs: Additional arguments passed to the underlying rule.

    Example:
      generate_sbom(
          name = "project_sbom",
          deps = [":my_app"],  # Will collect ALL transitive dependencies
          out = "project.spdx.json",
      )
    """
    if not out:
        out = name + ".spdx.json"

    _generate_sbom(
        name = name,
        deps = deps,
        out = out,
        **kwargs
    )
